import { createZodDto } from 'nestjs-zod';
import { isoDateSchema } from 'src/common/schemas/date.schema';
import { positiveMoneySchema } from 'src/common/schemas/money.schema';
import { z } from 'zod';

// Exactly one payer, by construction: the union admits one kind at a time,
// matching CHECK "Payment_exactly_one_payer".
const payerSchema = z.discriminatedUnion('kind', [
  // Registered and enrolled in the receiving program.
  z.object({ kind: z.literal('PERSON'), personId: z.string().min(1).max(64) }),
  // Another program paying out of its own funds.
  z.object({
    kind: z.literal('PROGRAM'),
    programId: z.string().min(1).max(64),
  }),
  // Someone not in the system at all — a one-off donor.
  z.object({
    kind: z.literal('FREETEXT'),
    name: z.string().trim().min(1).max(200),
  }),
]);

export const recordPaymentSchema = z.object({
  payer: payerSchema,
  amount: positiveMoneySchema,
  // The day the money arrived; the year every total files it under is
  // derived from it (CHECK "Payment_year_matches_date").
  paymentDate: isoDateSchema,
  // Generated by the form when it opens, so a double submit books once.
  idempotencyKey: z.uuid().optional(),
});

export class RecordPaymentDto extends createZodDto(recordPaymentSchema) {}
